github: martinrotter
liberapay: martinrotter
patreon: martinrotter
custom: ["https://www.blockchain.com/explorer/addresses/btc/bc1qc29vazm5akncs4ywgdu0kje4r8jtzfjfdxtzpa", "https://www.paypal.me/martinrot", 
