#!/bin/sh

# Replace dynamically generated date/times with static ones.
sed -i -E "s/TIMESTAMP YEAR \"[^\"]+\"/TIMESTAMP YEAR \"$(date +%Y)\"/" CMakeLists.txt
sed -i -E "s/TIMESTAMP DATE \"[^\"]+\"/TIMESTAMP DATE \"$(date +%Y-%m-%d)\"/" CMakeLists.txt

# Yes, I know.
git add CMakeLists.txt