#!/bin/sh

# Replace dynamically generated date/times with static ones.
cat CMakeLists.txt | sed -i -e "s/TIMESTAMP YEAR \"%Y\"/TIMESTAMP YEAR \"$(date +%Y)\"/" CMakeLists.txt
cat CMakeLists.txt | sed -i -e "s/TIMESTAMP DATE \"%Y-%m-%d\"/TIMESTAMP DATE \"$(date +%Y-%m-%d)\"/" CMakeLists.txt