#!/bin/sh

changelog_file="resources/text/CHANGELOG"
datestring="$(date +%F)"
versionstring="$(head -n 1 "$changelog_file")"

for appdata_file in resources/desktop/*.metainfo.xml.in; do
  appdata_file_n="${appdata_file}.n"

  # Set version and date.
  cat "$appdata_file" | sed -e "s@release version\=\"[A-Za-z0-9.]*\"@release version\=\"$versionstring\"@g" | sed -e "s@ date\=\"[0-9\-]*\"@ date\=\"$datestring\"@g" > "$appdata_file_n"
  mv "$appdata_file_n" "$appdata_file"

  git add "$appdata_file"
done

exit 0