#ifndef STANDARD_DEFINITIONS_H
#define STANDARD_DEFINITIONS_H

#define DEFAULT_FEED_ENCODING       "UTF-8"
#define DEFAULT_FEED_TYPE           "RSS"
#define MIN_CATEGORY_NAME_LENGTH    1
#define FEED_INITIAL_OPML_PATTERN   "feeds-%1.opml"

#endif // STANDARD_DEFINITIONS_H
